### PR TITLE
Fixes #37: Dialect validation errors not showing

### LINKED ISSUE #37: Dialect validation errors not showing
If I remove the `version` or any other mendatory nodes, there is an error in the JS console but it is not displayed to the user which makes it hard to figure what's happening.

### PR DESCRIPTION
**Pull request by postatum**
Fixes #37

~@jstoiko is alerting errors a good enough solution?~

### CODE REVIEW

**Comment by postatum** [comment]
Reworked to highlight errors in editors instead of alerting.

**Comment by postatum** [comment]
> It's much better. Can we highlight on the position of the error though? Like we do with the Document validation.
> 
> E.g. if I change L18 from `propertyTerm: schema-org.assemblyVersion` to `propertyTerm: assemblyVersion`, it should only highlight `assemblyVersion` (`[(18,22)-(18,37)]` in the Position property of the error...), not the entire Dialect

There's no simple way to extract lexical info from an AMF error because all its data is a string message. It's different from validation errors you see in Document editor because those aren't really js/java errors but validation results, which are objects with properties.

The only way to extract lexical info I can think of right now is parsing that error message to extract line-column from a message (e.g. `Position: Some(LexicalInformation([(18,22)-(18,37)]))`). Should I do it?

**Comment by postatum** [comment]
> can we also get rid of `Quick Fix...` and `Peek Problem` options in the error boxes? it doesn't really add anything since we're not providing any such "quick fix"...

Fixed

**Comment by jstoiko** [comment]
> Should I do it?
Yes.  

> There's no simple way to extract lexical info from an AMF error because all its data is a string message
Are you sure? AMF should provide some ways to retrieve/parse those errors without having to extract the info from the full error message.

**Comment by postatum** [comment]
@jstoiko I've reworked this a little and now it highlights proper area on local errors like the one you described with `propertyTerm: schema-org.assemblyVersion`. It still highlights all the editor on global errors which are related to a whole document though.

**Pull request merged**
